// Stand-ins for the XAML-backed types the checked sources call into.
//
// These exist only so the Linux compile-check can reach the code that matters.
// Their real versions live behind `.xaml.cs` files, whose `InitializeComponent`
// and named-element fields are generated by the Windows-only XAML compiler, so
// including them here is impossible.
//
// THE RISK, STATED PLAINLY: a stub that drifts from the real signature still
// compiles, so this check would pass while the Windows build fails. That is
// acceptable because the surface is tiny and deliberately so — four members —
// and CI on windows-2025 compiles the real thing on every push. Keep it that way:
// if a stub here needs to grow, that is a sign the notification code is reaching
// further into the host than it should, and the fix is usually in the caller.

using Microsoft.UI.Dispatching;

namespace Persistent.Desktop.Windows
{
    /// <summary>Stub of the flyout window. Real one: `Windows/AppFlyout.xaml.cs`.</summary>
    internal static class AppFlyout
    {
        public static Task<string?> GetSessionCookieAsync() => Task.FromResult<string?>(null);
        public static void Show() { }
        public static void NavigateToReminder(string reminderId) { }
    }
}

namespace Persistent.Desktop
{
    /// <summary>Stub of the application object. Real one: `App.xaml.cs`.</summary>
    internal static class App
    {
        public static DispatcherQueue MainDispatcherQueue => null!;
    }
}

namespace Persistent.Desktop.Classes
{
    /// <summary>
    /// Stub of the theme manager, which `UserSettings` calls on change. The real
    /// one takes a `Microsoft.UI.Xaml.Window` and reaches `SettingsWindow`.
    /// </summary>
    internal static class ThemeManager
    {
        public static void ApplyAndSaveTheme(int theme) { }
    }
}
